### ISSUE TITLE
Missing aes key as default key

### ISSUE THREAD

**Issue by ghost** [aaronk6/dsl-monitoring#2]
Hello, 

currently I am using a speedport 3 smart and try to decrypt the json, as in your smart4-vdsl file. My only question is: Where may I find the aes decryption key? 
So far everything from the _http://192.168.2.XXX/data/devicelist.json_ list could be downloaded but the output is either gibberish or ```Error decrypting data: MAC check failed```

Do you have something that may help me? 

Thank you in advance

**Comment by aaronk6** [comment]
Hi,

See if you find a function called `decryptccm` in http://192.168.2.XXX/js/jquery-addons.js. It should contain a variable called `keyArrayDefault` which holds the symmetric key used for encryption/decryption.

**Comment by ghost** [comment]
It does. Thank you :-)
